with-expecter: true
disable-version-string: true
filename: "mock_{{.InterfaceName | snakecase}}.go"
outpkg: "{{.PackageName}}mock"
dir: "{{.InterfaceDir}}/mocks"
all: false
issue-845-fix: true

packages:
  github.com/Crows-Storm/Axis/user/domain/user:
    # if want more interface: "(Repository|otherInterface)$"
    interfaces:
      Repository: {}

  github.com/Crows-Storm/Axis/user/protos:
    interfaces:
      ServerInterface: {}